/**
 * Client-safe list of AP.5 template keys (admin UI). Resolver lives in reportVariableResolver.ts.
 */

export const REPORT_VARIABLE_KEYS_AP5 = [
  "lagna",
  "lagna_sign",
  "lagna_lord",
  "sun_sign",
  "sun_house",
  "moon_sign",
  "moon_house",
  "moon_nakshatra",
  "mars_sign",
  "mars_house",
  "mercury_sign",
  "mercury_house",
  "jupiter_sign",
  "jupiter_house",
  "venus_sign",
  "venus_house",
  "saturn_sign",
  "saturn_house",
  "rahu_sign",
  "rahu_house",
  "ketu_sign",
  "ketu_house",
  "mahadasha_lord",
  "mahadasha_start_date",
  "mahadasha_end_date",
  "antardasha_lord",
  "antardasha_end_date",
  "arudha_lagna",
  "arudha_lagna_sign",
  "ghati_lagna",
  "ghati_lagna_sign",
  "bhava_lagna",
  "bhava_lagna_sign",
  "hora_lagna",
  "hora_lagna_sign",
  "atmakaraka",
  "amatyakaraka",
  "bhratrukaraka",
  "matrukaraka",
  "pitrukaraka",
  "putrakaraka",
  "gnatikaraka",
  "darakaraka",
  "hd_type",
  "hd_strategy",
  "hd_authority",
  "hd_profile",
  "hd_incarnation_cross",
  "hd_definition",
  "user_name",
  "birth_date",
  "birth_location",
] as const;

export type ReportVariableKeyAp5 = (typeof REPORT_VARIABLE_KEYS_AP5)[number];
