// STATUS: done | Report template placeholders
/**
 * Every {{placeholder}} supported by `buildReportTemplateVars` (admin UIs import this only).
 */
export const REPORT_TEMPLATE_VARIABLE_KEYS = [
  "user_email",
  "user_name",
  "birth_name",
  "birth_date",
  "birth_time",
  "birth_city",
  "birth_country",
  "birth_location",
  "birth_latitude",
  "birth_longitude",
  "timezone",
  "gender",
  "observation_city",
  "observation_latitude",
  "observation_longitude",
  "intake_life_situation",
  "intake_primary_focus",
  "intake_wants_clarity",
  "hd_type",
  "hd_strategy",
  "hd_authority",
  "hd_profile",
  "hd_definition",
  "hd_signature",
  "hd_not_self_theme",
  "hd_incarnation_cross_type",
  "hd_incarnation_cross_gates",
  "hd_incarnation_cross_json",
  "hd_defined_centers",
  "hd_undefined_centers",
  "hd_active_gates",
  "hd_active_channels_json",
  "hd_variables_json",
  "hd_personality_activations_json",
  "hd_design_activations_json",
  "hd_design_date",
  "lagna",
  "sun_sign",
  "moon_sign",
  "vedic_json",
  "vedic_planets_json",
  "vedic_houses_json",
  "sade_sati",
  "current_mahadasha",
  "current_antardasha",
  "current_dasha",
  "dashas_json",
  "transit_json",
  "transit_date",
  "today_date",
  "today_iso",

  // Vedic special points (foundation + extended; JSON mirrors KV cache)
  "sp_foundation_json",
  "sp_extended_json",
  "sp_arudha_sign",
  "sp_ghati_sign",
  "sp_bhava_sign",
  "sp_hora_sign",
  "sp_charakarakas_json",
  "sp_varnada_sign",
  "sp_pranapada_sign",
  "sp_upapada_sign",
  "sp_sree_sign",
  "sp_bhrigu_sign",
  "sp_bhrigu_longitude",
  "sp_beeja_sign",
  "sp_kshetra_sign",
  "sp_trisphuta_sign",
  "sp_trisphuta_longitude",
  "sp_dhooma_chain_json",
  "sp_kaal_velas_json",
] as const;

export type ReportTemplateVariableKey =
  (typeof REPORT_TEMPLATE_VARIABLE_KEYS)[number];
