/** Fallback when seed user shomty@hotmail.com is absent (AP.8). */
export const SAMPLE_REPORT_VARIABLES: Record<string, string> = {
  lagna: "4",
  lagna_sign: "Cancer",
  lagna_lord: "Moon",
  sun_sign: "Aries",
  sun_house: "10",
  moon_sign: "Taurus",
  moon_house: "11",
  moon_nakshatra: "Rohini",
  mars_sign: "Gemini",
  mars_house: "12",
  mercury_sign: "Cancer",
  mercury_house: "1",
  jupiter_sign: "Leo",
  jupiter_house: "2",
  venus_sign: "Virgo",
  venus_house: "3",
  saturn_sign: "Libra",
  saturn_house: "4",
  rahu_sign: "Scorpio",
  rahu_house: "5",
  ketu_sign: "Taurus",
  ketu_house: "11",
  mahadasha_lord: "Saturn",
  mahadasha_start_date: "2020-01-01",
  mahadasha_end_date: "2039-01-01",
  antardasha_lord: "Jupiter",
  antardasha_end_date: "2026-06-01",
  arudha_lagna: "7",
  arudha_lagna_sign: "Capricorn",
  ghati_lagna: "8",
  ghati_lagna_sign: "Aquarius",
  bhava_lagna: "9",
  bhava_lagna_sign: "Pisces",
  hora_lagna: "10",
  hora_lagna_sign: "Aries",
  atmakaraka: "Sun",
  amatyakaraka: "Mercury",
  bhratrukaraka: "Mars",
  matrukaraka: "Moon",
  pitrukaraka: "Sun",
  putrakaraka: "Jupiter",
  gnatikaraka: "Saturn",
  darakaraka: "Venus",
  hd_type: "Generator",
  hd_strategy: "Wait to respond",
  hd_authority: "Sacral",
  hd_profile: "3/5",
  hd_incarnation_cross: "Right Angle Cross of Explanation",
  hd_definition: "Single",
  user_name: "sample",
  birth_date: "March 15, 1988",
  birth_location: "Sample City, Earth",
};
